# Generated by Django 3.0 on 2019-12-16 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("byline", models.TextField(blank=True, null=True)),
                ("time_str", models.CharField(blank=True, max_length=255, null=True)),
                ("body_content", models.TextField(blank=True, null=True)),
                ("article_time", models.DateTimeField(blank=True, null=True)),
                (
                    "url",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("url_no_schema", models.TextField(blank=True, null=True)),
                (
                    "rip_type",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "<unknown>"),
                            ("CNN", "CNN"),
                            ("NYT", "New York Times"),
                            ("WAPO", "Washington Post"),
                            ("POLITICO", "Politico"),
                            ("HILL", "The Hill"),
                        ],
                        default="UNKNOWN",
                        max_length=9,
                    ),
                ),
                ("rip_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CNNArticle",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("ripper.article",),
        ),
        migrations.CreateModel(
            name="HillArticle",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("ripper.article",),
        ),
        migrations.CreateModel(
            name="NYTArticle",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("ripper.article",),
        ),
        migrations.CreateModel(
            name="PoliticoArticle",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("ripper.article",),
        ),
        migrations.CreateModel(
            name="WAPOArticle",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("ripper.article",),
        ),
    ]
