# Generated by Django 3.0.2 on 2020-02-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ripper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="manual",
            field=models.BooleanField(default=False),
        ),
    ]
